### PR TITLE
Kathy's updated files

### PR DESCRIPTION
**Pull request by KathyGray**
My updates are worthy of being in your repository (I hope) so please accept them.

### CODE REVIEW

**Comment by roualdes** [comment]
Thanks for going this route, @KathyGray. It takes a bit to get the hang of it, but it's pretty clean once going.

May I request a few changes before accepting?

Would you mind sourcing all the PNG files from the math105 folder and then deleting the duplicates (or any remaining PNGs) from the public folder itself? This will help me minimize copying to my actual website folder.

If you want to rename the math105 folder to something more general so that it makes sense to you to include math450 images in it also, please do.  Alternatively, you could create a math450 folder `public/math450` in which to store your math450 images.

Thanks.

**Comment by KathyGray** [comment]
Hi there! I think I did what you asked which was deleted the files from /Public. I also needed to update line 55 of app.js to reflect that the images are no located in /Public/math105. Everything runs on my computer so hopefully good to go.

**Comment by roualdes** [comment]
Unfortunately, changing line 55 of app.js wrecks a number of other parts of my website that rely on public being the root directory of all static assets.  Would you please change this line back?  The requested changes below should be satisfy both of our needs.

I should have been more clear that we should change the lab0X.pug image source paths, for all math105 and math450 images.  They used to be, as they should be, `src="/math105/teddy_bears.PNG"`, but for some reason got changed to `src="/teddy_bears.PNG"`.  Did this not work for you?  Or did I just explain it poorly?  Would you mind changing these lines from `src="/teddy_bears.PNG"` to `src="/math105/teddy_bears.PNG"`?  If you need me to point out these lines to you specifically, I can.

Once I accept this pull request, I'll close it.  If you close it before I accept it, then I can not accept it.

**Comment by KathyGray** [comment]
Hi Edward! Sorry about that. Like I said, I know just enough to be dangerous. I am getting the hang of things though.

All the labXX.pug files have the correct sourcing and I changed the app.js file back to what you had. I will remember that changing the other files affects things beyond just me.

I did another pull request.

Thanks again,

Kathy

**Pull request closed without merging**
